// curriculum-standards.ts
// Full skill taxonomy for WonderQuest Learning.
// Skill codes match what is stored in the DB (student_skill_mastery.skill_code).

export type SkillSubject = "math" | "reading" | "science" | "logic";
// Priority maps to the learning tier shown in the parent UI:
//   "must-have"    → 🎯 Essential   — core standards, grade-level requirements
//   "should-have"  → 📗 On Track    — grade benchmarks, expected competency
//   "nice-to-have" → ⭐ Enrichment  — beyond grade level, well-rounded
//   "could-have"   → 🚀 Challenge   — advanced / next-grade exploration
export type SkillPriority = "must-have" | "should-have" | "nice-to-have" | "could-have";
export type SkillComplexity = 1 | 2 | 3;
export type SkillActivityType = "drill" | "story" | "explore" | "puzzle";
export type BandCode = "PREK" | "K1" | "G23" | "G45";

export interface CurriculumSkill {
  code: string;
  name: string;
  subject: SkillSubject;
  priority: SkillPriority;
  complexity: SkillComplexity;
  activityType: SkillActivityType;
  description: string;
  bandCode: BandCode;
}

export const CURRICULUM: CurriculumSkill[] = [
  // ─── PREK — Essential (🎯) ────────────────────────────────────────────────────────
  {
    code: "color-recognition",
    name: "Color Recognition",
    subject: "math",
    priority: "must-have",
    complexity: 1,
    activityType: "drill",
    description: "Identify and name basic colors such as red, blue, green, and yellow.",
    bandCode: "PREK",
  },
  {
    code: "shape-circle",
    name: "Circle Recognition",
    subject: "math",
    priority: "must-have",
    complexity: 1,
    activityType: "drill",
    description: "Recognize and name the shape of a circle in everyday objects.",
    bandCode: "PREK",
  },
  {
    code: "count-to-3",
    name: "Count to 3",
    subject: "math",
    priority: "must-have",
    complexity: 1,
    activityType: "drill",
    description: "Count a small set of objects up to three using one-to-one correspondence.",
    bandCode: "PREK",
  },
  {
    code: "bigger-smaller",
    name: "Bigger and Smaller",
    subject: "math",
    priority: "must-have",
    complexity: 1,
    activityType: "puzzle",
    description: "Compare two objects or groups and identify which is bigger or smaller.",
    bandCode: "PREK",
  },

  // ─── PREK — On Track (📗) ──────────────────────────────────────────────────────
  {
    code: "letter-a-recognition",
    name: "Letter A Recognition",
    subject: "reading",
    priority: "should-have",
    complexity: 1,
    activityType: "drill",
    description: "Identify the uppercase and lowercase letter A by sight.",
    bandCode: "PREK",
  },
  {
    code: "letter-b-recognition",
    name: "Letter B Recognition",
    subject: "reading",
    priority: "should-have",
    complexity: 1,
    activityType: "drill",
    description: "Identify the uppercase and lowercase letter B by sight.",
    bandCode: "PREK",
  },
  {
    code: "rhyme-basic",
    name: "Basic Rhyming",
    subject: "reading",
    priority: "should-have",
    complexity: 1,
    activityType: "story",
    description: "Recognize pairs of words that rhyme and complete simple rhyming patterns.",
    bandCode: "PREK",
  },
  {
    code: "pattern-ab-basic",
    name: "AB Pattern Basics",
    subject: "logic",
    priority: "should-have",
    complexity: 1,
    activityType: "puzzle",
    description: "Identify and extend a simple alternating AB pattern using shapes or colors.",
    bandCode: "PREK",
  },

  // ─── PREK — Enrichment (⭐) ─────────────────────────────────────────────────────
  {
    code: "animal-sounds",
    name: "Animal Sounds",
    subject: "science",
    priority: "nice-to-have",
    complexity: 1,
    activityType: "explore",
    description: "Match common animals to the sounds they make.",
    bandCode: "PREK",
  },
  {
    code: "body-parts",
    name: "Body Parts",
    subject: "science",
    priority: "nice-to-have",
    complexity: 1,
    activityType: "explore",
    description: "Identify and name basic body parts such as head, hands, and feet.",
    bandCode: "PREK",
  },
  {
    code: "same-different",
    name: "Same and Different",
    subject: "logic",
    priority: "nice-to-have",
    complexity: 1,
    activityType: "puzzle",
    description: "Sort objects by identifying which ones are the same and which are different.",
    bandCode: "PREK",
  },

  // ─── PREK — Challenge (🚀) ───────────────────────────────────────────────────────
  {
    code: "season-basic",
    name: "Basic Seasons",
    subject: "science",
    priority: "could-have",
    complexity: 1,
    activityType: "explore",
    description: "Recognize the four seasons and describe a simple characteristic of each.",
    bandCode: "PREK",
  },
  {
    code: "feelings-basic",
    name: "Basic Feelings",
    subject: "logic",
    priority: "could-have",
    complexity: 1,
    activityType: "story",
    description: "Identify and name basic emotions such as happy, sad, and angry through pictures.",
    bandCode: "PREK",
  },

  // ─── K1 — Essential (🎯) ──────────────────────────────────────────────────────────
  {
    code: "add-to-10",
    name: "Add to 10",
    subject: "math",
    priority: "must-have",
    complexity: 1,
    activityType: "drill",
    description: "Solve addition problems where both addends and the sum are 10 or less.",
    bandCode: "K1",
  },
  {
    code: "sight-words-basic",
    name: "Basic Sight Words",
    subject: "reading",
    priority: "must-have",
    complexity: 1,
    activityType: "drill",
    description: "Read and recognize a foundational set of high-frequency sight words on sight.",
    bandCode: "K1",
  },
  {
    code: "read-simple-word",
    name: "Read Simple Words",
    subject: "reading",
    priority: "must-have",
    complexity: 1,
    activityType: "story",
    description: "Decode and read short, simple words using letter-sound knowledge.",
    bandCode: "K1",
  },
  {
    code: "short-a-sound",
    name: "Short A Sound",
    subject: "reading",
    priority: "must-have",
    complexity: 1,
    activityType: "drill",
    description: "Identify and produce the short /a/ vowel sound in spoken and written words.",
    bandCode: "K1",
  },

  // ─── K1 — On Track (📗) ────────────────────────────────────────────────────────
  {
    code: "short-e-sound",
    name: "Short E Sound",
    subject: "reading",
    priority: "should-have",
    complexity: 2,
    activityType: "drill",
    description: "Identify and produce the short /e/ vowel sound in spoken and written words.",
    bandCode: "K1",
  },
  {
    code: "short-i-sound",
    name: "Short I Sound",
    subject: "reading",
    priority: "should-have",
    complexity: 2,
    activityType: "drill",
    description: "Identify and produce the short /i/ vowel sound in spoken and written words.",
    bandCode: "K1",
  },
  {
    code: "count-to-20",
    name: "Count to 20",
    subject: "math",
    priority: "should-have",
    complexity: 1,
    activityType: "drill",
    description: "Count forward from any number up to 20 using objects or a number line.",
    bandCode: "K1",
  },
  {
    code: "subtract-to-10",
    name: "Subtract Within 10",
    subject: "math",
    priority: "should-have",
    complexity: 2,
    activityType: "drill",
    description: "Solve subtraction problems where the minuend and result are 10 or less.",
    bandCode: "K1",
  },

  // ─── K1 — Enrichment (⭐) ───────────────────────────────────────────────────────
  {
    code: "sentence-building",
    name: "Sentence Building",
    subject: "reading",
    priority: "nice-to-have",
    complexity: 2,
    activityType: "story",
    description: "Arrange words in the correct order to form a complete, meaningful sentence.",
    bandCode: "K1",
  },
  {
    code: "main-idea",
    name: "Main Idea",
    subject: "reading",
    priority: "nice-to-have",
    complexity: 2,
    activityType: "story",
    description: "Identify the central topic or main idea of a short passage or image set.",
    bandCode: "K1",
  },
  {
    code: "time-to-hour",
    name: "Time to the Hour",
    subject: "math",
    priority: "nice-to-have",
    complexity: 2,
    activityType: "puzzle",
    description: "Read an analog or digital clock and tell time to the nearest hour.",
    bandCode: "K1",
  },
  {
    code: "shape-3d-basic",
    name: "Basic 3D Shapes",
    subject: "math",
    priority: "nice-to-have",
    complexity: 2,
    activityType: "explore",
    description: "Identify and name basic three-dimensional shapes such as sphere, cube, and cone.",
    bandCode: "K1",
  },

  // ─── K1 — Challenge (🚀) ─────────────────────────────────────────────────────────
  {
    code: "life-cycle-basics",
    name: "Life Cycle Basics",
    subject: "science",
    priority: "could-have",
    complexity: 2,
    activityType: "explore",
    description: "Describe the basic stages in the life cycle of a familiar animal or plant.",
    bandCode: "K1",
  },
  {
    code: "weather-types",
    name: "Weather Types",
    subject: "science",
    priority: "could-have",
    complexity: 1,
    activityType: "explore",
    description: "Identify and describe common types of weather such as sunny, rainy, and snowy.",
    bandCode: "K1",
  },
  {
    code: "pattern-next-item",
    name: "Pattern: Next Item",
    subject: "logic",
    priority: "could-have",
    complexity: 2,
    activityType: "puzzle",
    description: "Determine what comes next in a repeating or growing pattern.",
    bandCode: "K1",
  },

  // ─── G23 — Essential (🎯) ─────────────────────────────────────────────────────────
  {
    code: "add-3-digit",
    name: "Add 3-Digit Numbers",
    subject: "math",
    priority: "must-have",
    complexity: 2,
    activityType: "drill",
    description: "Add two three-digit numbers with and without regrouping.",
    bandCode: "G23",
  },
  {
    code: "multiply-3x4",
    name: "Multiply Within 3s and 4s",
    subject: "math",
    priority: "must-have",
    complexity: 2,
    activityType: "drill",
    description: "Recall and apply multiplication facts for the 3 and 4 times tables.",
    bandCode: "G23",
  },
  {
    code: "main-idea",
    name: "Main Idea",
    subject: "reading",
    priority: "must-have",
    complexity: 2,
    activityType: "story",
    description: "Identify the main idea of a passage and explain how key details support it.",
    bandCode: "G23",
  },
  {
    code: "cause-effect",
    name: "Cause and Effect",
    subject: "reading",
    priority: "must-have",
    complexity: 2,
    activityType: "story",
    description: "Identify cause-and-effect relationships in a text and explain them in sequence.",
    bandCode: "G23",
  },

  // ─── G23 — On Track (📗) ───────────────────────────────────────────────────────
  {
    code: "skip-count-by-5",
    name: "Skip Count by 5s",
    subject: "math",
    priority: "should-have",
    complexity: 1,
    activityType: "drill",
    description: "Count forward and backward by fives starting from any multiple of five.",
    bandCode: "G23",
  },
  {
    code: "compare-numbers",
    name: "Compare Numbers",
    subject: "math",
    priority: "should-have",
    complexity: 2,
    activityType: "puzzle",
    description: "Use symbols (<, >, =) to compare two multi-digit whole numbers.",
    bandCode: "G23",
  },
  {
    code: "time-to-hour",
    name: "Time to the Hour",
    subject: "math",
    priority: "should-have",
    complexity: 2,
    activityType: "puzzle",
    description: "Read an analog or digital clock and tell time to the nearest hour.",
    bandCode: "G23",
  },
  {
    code: "paragraph-sequence",
    name: "Paragraph Sequence",
    subject: "reading",
    priority: "should-have",
    complexity: 2,
    activityType: "story",
    description: "Arrange sentences or events from a passage into the correct logical order.",
    bandCode: "G23",
  },

  // ─── G23 — Enrichment (⭐) ──────────────────────────────────────────────────────
  {
    code: "life-cycle-basics",
    name: "Life Cycle Basics",
    subject: "science",
    priority: "nice-to-have",
    complexity: 2,
    activityType: "explore",
    description: "Describe the basic stages in the life cycle of a familiar animal or plant.",
    bandCode: "G23",
  },
  {
    code: "pattern-next-item",
    name: "Pattern: Next Item",
    subject: "logic",
    priority: "nice-to-have",
    complexity: 2,
    activityType: "puzzle",
    description: "Determine what comes next in a repeating or growing pattern.",
    bandCode: "G23",
  },
  {
    code: "fraction-half",
    name: "Fractions: One Half",
    subject: "math",
    priority: "nice-to-have",
    complexity: 3,
    activityType: "puzzle",
    description: "Identify and represent one half of a shape, set, or number line segment.",
    bandCode: "G23",
  },
  {
    code: "measurement-cm",
    name: "Measurement in Centimeters",
    subject: "math",
    priority: "nice-to-have",
    complexity: 2,
    activityType: "drill",
    description: "Measure the length of objects to the nearest centimeter using a ruler.",
    bandCode: "G23",
  },

  // ─── G23 — Challenge (🚀) ────────────────────────────────────────────────────────
  {
    code: "earth-layers",
    name: "Earth's Layers",
    subject: "science",
    priority: "could-have",
    complexity: 3,
    activityType: "explore",
    description: "Identify and describe the basic layers of the Earth: crust, mantle, and core.",
    bandCode: "G23",
  },
  {
    code: "story-character",
    name: "Story Character",
    subject: "reading",
    priority: "could-have",
    complexity: 2,
    activityType: "story",
    description: "Describe a character's traits, feelings, and motivations based on story events.",
    bandCode: "G23",
  },
  {
    code: "data-bar-chart",
    name: "Data: Bar Charts",
    subject: "math",
    priority: "could-have",
    complexity: 3,
    activityType: "puzzle",
    description: "Read and interpret a bar chart to answer questions about data.",
    bandCode: "G23",
  },

  // ─── G45 — Essential (🎯) ─────────────────────────────────────────────────────────
  {
    code: "multiply-3x4",
    name: "Multiply Within 3s and 4s",
    subject: "math",
    priority: "must-have",
    complexity: 2,
    activityType: "drill",
    description: "Recall and apply multiplication facts for the 3 and 4 times tables.",
    bandCode: "G45",
  },
  {
    code: "fraction-half",
    name: "Fractions: One Half",
    subject: "math",
    priority: "must-have",
    complexity: 3,
    activityType: "puzzle",
    description: "Identify and represent one half of a shape, set, or number line segment.",
    bandCode: "G45",
  },
  {
    code: "cause-effect",
    name: "Cause and Effect",
    subject: "reading",
    priority: "must-have",
    complexity: 3,
    activityType: "story",
    description: "Identify cause-and-effect relationships in a text and explain them in sequence.",
    bandCode: "G45",
  },
  {
    code: "data-bar-chart",
    name: "Data: Bar Charts",
    subject: "math",
    priority: "must-have",
    complexity: 3,
    activityType: "puzzle",
    description: "Read and interpret a bar chart to answer questions about data.",
    bandCode: "G45",
  },

  // ─── G45 — On Track (📗) ───────────────────────────────────────────────────────
  {
    code: "long-division",
    name: "Long Division",
    subject: "math",
    priority: "should-have",
    complexity: 3,
    activityType: "drill",
    description: "Divide multi-digit numbers using the standard long division algorithm.",
    bandCode: "G45",
  },
  {
    code: "paragraph-sequence",
    name: "Paragraph Sequence",
    subject: "reading",
    priority: "should-have",
    complexity: 3,
    activityType: "story",
    description: "Arrange sentences or events from a passage into the correct logical order.",
    bandCode: "G45",
  },
  {
    code: "measurement-cm",
    name: "Measurement in Centimeters",
    subject: "math",
    priority: "should-have",
    complexity: 2,
    activityType: "drill",
    description: "Measure the length of objects to the nearest centimeter using a ruler.",
    bandCode: "G45",
  },
  {
    code: "compare-numbers",
    name: "Compare Numbers",
    subject: "math",
    priority: "should-have",
    complexity: 3,
    activityType: "puzzle",
    description: "Use symbols (<, >, =) to compare two multi-digit whole numbers.",
    bandCode: "G45",
  },

  // ─── G45 — Enrichment (⭐) ──────────────────────────────────────────────────────
  {
    code: "earth-layers",
    name: "Earth's Layers",
    subject: "science",
    priority: "nice-to-have",
    complexity: 3,
    activityType: "explore",
    description: "Identify and describe the basic layers of the Earth: crust, mantle, and core.",
    bandCode: "G45",
  },
  {
    code: "story-character",
    name: "Story Character",
    subject: "reading",
    priority: "nice-to-have",
    complexity: 3,
    activityType: "story",
    description: "Describe a character's traits, feelings, and motivations based on story events.",
    bandCode: "G45",
  },
  {
    code: "pattern-complex",
    name: "Complex Patterns",
    subject: "logic",
    priority: "nice-to-have",
    complexity: 3,
    activityType: "puzzle",
    description: "Identify and extend multi-step or growing patterns using numbers or shapes.",
    bandCode: "G45",
  },
  {
    code: "estimation-round",
    name: "Estimation and Rounding",
    subject: "math",
    priority: "nice-to-have",
    complexity: 3,
    activityType: "drill",
    description: "Round whole numbers to the nearest ten or hundred to estimate sums and differences.",
    bandCode: "G45",
  },

  // ─── G45 — Challenge (🚀) ────────────────────────────────────────────────────────
  {
    code: "energy-forms",
    name: "Forms of Energy",
    subject: "science",
    priority: "could-have",
    complexity: 3,
    activityType: "explore",
    description: "Identify and describe different forms of energy such as heat, light, and sound.",
    bandCode: "G45",
  },
  {
    code: "persuasive-text",
    name: "Persuasive Text",
    subject: "reading",
    priority: "could-have",
    complexity: 3,
    activityType: "story",
    description: "Identify the author's claim and key reasons in a persuasive passage.",
    bandCode: "G45",
  },
  {
    code: "geometry-area",
    name: "Geometry: Area",
    subject: "math",
    priority: "could-have",
    complexity: 3,
    activityType: "puzzle",
    description: "Calculate the area of rectangles and irregular shapes using square units.",
    bandCode: "G45",
  },
];

export function getCurriculumForBand(bandCode: string): CurriculumSkill[] {
  return CURRICULUM.filter((skill) => skill.bandCode === bandCode);
}

export function getMustHaveSkills(bandCode: string): CurriculumSkill[] {
  return CURRICULUM.filter(
    (skill) => skill.bandCode === bandCode && skill.priority === "must-have",
  );
}
